// Small product database (20 mattress products). Edit / add items here.
window.PRODUCTS = [
  {
    id: "spinecare-plus",
    name: "Orthomedic SpineCare Plus",
    category: "Mattress",
    shortDescription: "Firm support with zoned layers for spinal alignment and pressure relief.",
    fullDescription: "SpineCare Plus uses zoned support foam and a breathable top layer to maintain neutral spine alignment and reduce pressure points for restorative sleep.",
    features: ["Zoned foam support", "Breathable knit cover", "Hypoallergenic core"],
    idealFor: "Back pain sufferers, post-op recovery, clinics",
    careInstructions: ["Spot clean cover", "Avoid direct sunlight for prolonged periods", "Rotate mattress every 3 months"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic SpineCare Plus. Please share details."
  },
  {
    id: "ortho-pro",
    name: "Orthomedic Ortho Pro",
    category: "Mattress",
    shortDescription: "Balanced medium-firm mattress with targeted lumbar reinforcement.",
    fullDescription: "Ortho Pro combines contouring foams with reinforced lumbar support to help maintain healthy posture while providing comfortable cushioning.",
    features: ["Lumbar reinforcement", "Medium-firm feel", "Removable cover"],
    idealFor: "Those with chronic back discomfort and sleepers who prefer medium-firm support",
    careInstructions: ["Vacuum cover regularly", "Spot clean only", "Rotate every 2–3 months"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Ortho Pro. Please share details."
  },
  {
    id: "memoryflex",
    name: "Orthomedic MemoryFlex",
    category: "Mattress",
    shortDescription: "Adaptive memory foam comfort layer with supportive base for pressure relief.",
    fullDescription: "MemoryFlex molds to body contours to relieve pressure points while a supportive base maintains proper alignment and resilience.",
    features: ["Adaptive memory foam", "Support core", "Temperature regulating"],
    idealFor: "Side sleepers and people with joint pressure points",
    careInstructions: ["Use mattress protector", "Spot clean cover only"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic MemoryFlex. Please share details."
  },
  {
    id: "posture-support",
    name: "Orthomedic Posture Support",
    category: "Mattress",
    shortDescription: "Firm base with ergonomic top layer for sustained posture correction.",
    fullDescription: "Posture Support mattress encourages neutral spinal alignment with an ergonomic top layer for targeted cushioning and durable support.",
    features: ["Ergonomic top layer", "Firm support core", "Anti-microbial cover"],
    idealFor: "Patients undergoing physiotherapy and users seeking firmer support",
    careInstructions: ["Air out before first use", "Spot clean cover"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Posture Support. Please share details."
  },
  {
    id: "silver-care",
    name: "Orthomedic Silver Care",
    category: "Mattress",
    shortDescription: "Silver-infused top layer for hygiene and gentle support.",
    fullDescription: "Silver Care uses an antimicrobial silver-infused layer for enhanced hygiene and a medium support core suitable for family use.",
    features: ["Silver-infused fabric", "Medium support", "Hypoallergenic"],
    idealFor: "Families and those seeking hygienic sleep surfaces",
    careInstructions: ["Machine-washable cover", "Do not tumble dry cover"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Silver Care. Please share details."
  },
  {
    id: "pressure-relief",
    name: "Orthomedic Pressure Relief",
    category: "Mattress",
    shortDescription: "Contour layers to distribute pressure and reduce ache points.",
    fullDescription: "Pressure Relief features zoned contouring to distribute weight evenly and reduce pressure on shoulders and hips.",
    features: ["Zoned contouring", "Motion isolation", "Removable cover"],
    idealFor: "Side sleepers and those with chronic pressure-sensitive areas",
    careInstructions: ["Use protector", "Rotate periodically"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Pressure Relief. Please share details."
  },
  {
    id: "clinic-support",
    name: "Orthomedic Clinic Support",
    category: "Mattress",
    shortDescription: "Durable mattress tailored for clinics and healthcare facilities.",
    fullDescription: "Built for durability with an easy-clean surface and firm supportive core suitable for healthcare environments.",
    features: ["Durable construction", "Easy-clean surface", "Firm support"],
    idealFor: "Hospitals, clinics and nursing care",
    careInstructions: ["Wipe with mild detergent", "Avoid abrasive cleaners"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Clinic Support. Please share details."
  },
  {
    id: "recovery-aid",
    name: "Orthomedic Recovery Aid",
    category: "Mattress",
    shortDescription: "Soft comfort layer with pressure redistribution for recovery needs.",
    fullDescription: "Recovery Aid aims to reduce localized pressure and improve comfort during recovery phases with a forgiving comfort layer.",
    features: ["Pressure redistribution", "Comfort foam", "Breathable"],
    idealFor: "Post-surgery recovery and convalescence",
    careInstructions: ["Use waterproof protector if needed", "Rotate regularly"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Recovery Aid. Please share details."
  },
  {
    id: "cool-rest",
    name: "Orthomedic Cool Rest",
    category: "Mattress",
    shortDescription: "Cooling surface and breathable core for hot sleepers.",
    fullDescription: "Cool Rest integrates cooling gel layers and an airflow core to help maintain a comfortable sleeping temperature.",
    features: ["Cooling gel layer", "Airflow core", "Breathable cover"],
    idealFor: "Hot sleepers and humid climates",
    careInstructions: ["Avoid direct sunlight for cover", "Spot clean"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Cool Rest. Please share details."
  },
  {
    id: "orthopedic-eco",
    name: "Orthomedic Eco Ortho",
    category: "Mattress",
    shortDescription: "Eco-friendly materials with orthopedic support.",
    fullDescription: "Eco Ortho uses responsibly sourced materials and provides firm orthopaedic support with reduced environmental impact.",
    features: ["Eco materials", "Firm support", "Anti-microbial"],
    idealFor: "Environmentally conscious buyers and clinics",
    careInstructions: ["Spot clean", "Rotate occasionally"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Eco Ortho. Please share details."
  },
  {
    id: "adaptive-relief",
    name: "Orthomedic Adaptive Relief",
    category: "Mattress",
    shortDescription: "Adaptive foam layers for responsive pressure relief.",
    fullDescription: "Adaptive Relief blends responsive foam layers providing adaptive support and improved comfort for varied sleeping positions.",
    features: ["Adaptive layers", "Motion isolation", "Support core"],
    idealFor: "Combination sleepers and partners with different needs",
    careInstructions: ["Use protector", "Spot clean cover"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Adaptive Relief. Please share details."
  },
  {
    id: "clinic-premium",
    name: "Orthomedic Clinic Premium",
    category: "Mattress",
    shortDescription: "Premium clinic-grade mattress with enhanced hygiene and support.",
    fullDescription: "Clinic Premium offers superior build quality, reinforced seams and easy-clean materials suitable for demanding environments.",
    features: ["Reinforced seams", "Easy-clean", "Premium core"],
    idealFor: "Hospitals and rehabilitation centers",
    careInstructions: ["Wipe with mild disinfectant", "Avoid soaking"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Clinic Premium. Please share details."
  },
  {
    id: "sleep-assist",
    name: "Orthomedic Sleep Assist",
    category: "Mattress",
    shortDescription: "Balanced comfort mattress designed to assist better rest for seniors.",
    fullDescription: "Sleep Assist provides easy-entry comfort and stable support to help seniors move and rest comfortably without sacrificing pressure relief.",
    features: ["Stable support", "Easy-entry height", "Comfort foam"],
    idealFor: "Seniors and assisted living facilities",
    careInstructions: ["Use protector", "Rotate periodically"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Sleep Assist. Please share details."
  },
  {
    id: "pressure-min",
    name: "Orthomedic Pressure Min",
    category: "Mattress",
    shortDescription: "Highly contouring surface to minimize shear and pressure.",
    fullDescription: "Pressure Min is engineered to reduce shear and pressure for those who need extended bed rest with a focus on tissue protection.",
    features: ["Shear reduction", "High contouring", "Pressure redistribution"],
    idealFor: "Patients on prolonged bed rest",
    careInstructions: ["Use waterproof cover", "Follow clinic cleaning protocols"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Pressure Min. Please share details."
  },
  {
    id: "ortho-lite",
    name: "Orthomedic Ortho Lite",
    category: "Mattress",
    shortDescription: "Lightweight orthopedic mattress for portability and support.",
    fullDescription: "Ortho Lite is easier to handle and move while providing core orthopedic support for light care scenarios.",
    features: ["Lightweight", "Core support", "Portable"],
    idealFor: "Home care and temporary recovery",
    careInstructions: ["Keep dry", "Spot clean"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Ortho Lite. Please share details."
  },
  {
    id: "pressure-balance",
    name: "Orthomedic Pressure Balance",
    category: "Mattress",
    shortDescription: "Multi-layer system balancing comfort and high support.",
    fullDescription: "Pressure Balance blends top comfort layers with a high-support base to offer sag resistance and long-term alignment.",
    features: ["Multi-layer system", "Sag resistant", "Comfort wrap cover"],
    idealFor: "Couples and long-term daily use",
    careInstructions: ["Rotate occasionally", "Keep cover clean"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Pressure Balance. Please share details."
  },
  {
    id: "orthomedic-fresh",
    name: "Orthomedic Fresh",
    category: "Mattress",
    shortDescription: "Fresh fabric and airflow core for hygienic sleeping.",
    fullDescription: "Fresh mattress uses antimicrobial fabrics and an airflow core to keep sleeping surfaces clean and comfortable.",
    features: ["Antimicrobial fabric", "Airflow core", "Breathable"],
    idealFor: "Allergy sufferers and hygienic environments",
    careInstructions: ["Wash cover as per label", "Spot clean foam"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Fresh. Please share details."
  },
  {
    id: "comfort-support",
    name: "Orthomedic Comfort Support",
    category: "Mattress",
    shortDescription: "Balanced feel mattress offering everyday comfort and support.",
    fullDescription: "Comfort Support provides an all-round balance of cushioning and support suitable for a wide range of sleepers.",
    features: ["Balanced feel", "Edge support", "Durable foam"],
    idealFor: "Families and daily use",
    careInstructions: ["Rotate often", "Use protector"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Comfort Support. Please share details."
  },
  {
    id: "premium-orthoped",
    name: "Orthomedic Premium Orthoped",
    category: "Mattress",
    shortDescription: "Premium materials for long-lasting orthopedic support and comfort.",
    fullDescription: "Premium Orthoped features high-density foam layers and a premium cover crafted for longevity and support.",
    features: ["High-density support", "Premium cover", "Long-lasting"],
    idealFor: "Users who want premium long-term support",
    careInstructions: ["Follow label for washing", "Rotate every 3 months"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Premium Orthoped. Please share details."
  },
  {
    id: "orthomedic-lite-foam",
    name: "Orthomedic Lite Foam",
    category: "Mattress",
    shortDescription: "Economical orthopedic mattress for essential support.",
    fullDescription: "Lite Foam is an affordable option providing necessary support for shorter term or budget-conscious buyers without compromising on orthopedic design.",
    features: ["Economical", "Essential support", "Lightweight"],
    idealFor: "Budget-conscious buyers, guest rooms",
    careInstructions: ["Use protector", "Spot clean"],
    image: "images/demo.png",
    whatsappMessageText: "Hi, I’m interested in Orthomedic Lite Foam. Please share details."
  }
];